### ISSUE TITLE
saving function?

### ISSUE THREAD

**Issue by Jim-JZ-Chen** [daishihmr/vox.js#10]
can you make to saving function that pares a Voxeldata back to .vox format steam pls?

**Comment by daishihmr** [comment]
Someday I will make it... (/･ω･)/

**Comment by Jim-JZ-Chen** [comment]
thank you very much, i need it in my project. hopefully I can hear you soon, at the meantime, I will try to read your parser.js  see if I can figure it out by myself.

**Comment by greentec** [comment]
@Jim-JZ-Chen If you need saving function, maybe I have a temporary solution. 
I can't remember how I write this code, but I'm using this in my project.
Any question is welcome.

`
function VOX_Data(X, Y, Z, palette) {
	this.X = X;
	this.Y = Y;
	this.Z = Z;
	this.vcount = 0;
	this.voxels = [];

	this.palette = palette || [];

	if (this.palette.length == 0) {
		for (let i = 255; i > -1; i--) {
			this.palette.push(0xff000000 | i | (i << 8) | (i << 16));
		}
	}

	this.setVoxel = function(x, y, z, i) {
		i |= 0;
		x |= 0;
		y |= 0;
		z |= 0;

		if (i >= 0 && i < 256 && x >= 0 && y >= 0 && z >= 0 && x < this.X && y < this.Y && z < this.Z) {
			var key = x + "_" + y + "_" + z;
			if (i > 0) {
				if (!this.voxels[key]) this.vcount++;
				this.voxels[key] = i;
			} else {
				if (this.voxels[key]) this.vcount--;
				delete this.voxels[key];
			}
		}
	}

	this.appendString = function(data, str) {
		for (var i = 0, j = str.length; i < j; ++i) {
		  data.push(str.charCodeAt(i));
		}
	}

	this.appendUInt32 = function(data, n) {
		data.push(n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff);
	}

	this.appendRGBA = function(data, n) {
		data.push((n >>> 16) & 0xff,(n >>> 8) & 0xff, n & 0xff, (n >>> 24) & 0xff);
	}

	this.appendVoxel = function(data, key) {
		var v = key.split("_");
		data.push(v[0], v[1], v[2], this.voxels[key]);
	}

	this.export = function(filename) {
		var data = [];
		this.appendString(data, "VOX ");
		this.appendUInt32(data, 150);
		this.appendString(data, "MAIN");
		this.appendUInt32(data, 0);
		this.appendUInt32(data, this.vcount * 4 + 0x434);

		this.appendString(data, "SIZE");
		this.appendUInt32(data, 12);
		this.appendUInt32(data, 0);
		this.appendUInt32(data, this.X);
		this.appendUInt32(data, this.Y);
		this.appendUInt32(data, this.Z);
		this.appendString(data, "XYZI");
		this.appendUInt32(data, 4 + this.vcount * 4);
		this.appendUInt32(data, 0);
		this.appendUInt32(data, this.vcount);

		for (var key in this.voxels) {
			this.appendVoxel(data, key);
		}
			
		this.appendString(data, "RGBA");
		this.appendUInt32(data, 0x400);
		this.appendUInt32(data, 0);
				
		for (var i = 0; i < 256; i++) {
			this.appendRGBA(data, this.palette[i]);
		}
			
		this.saveByteArray([new Uint8Array(data)], filename);
		return;
	}

	this.saveByteArray = (function() {
		var a = document.createElement("a");
		document.body.appendChild(a);
		a.style = "display: none";
		return function(data, name) {
			var blob = new Blob(data, {
				type: "octet/stream"
			}),
			url = window.URL.createObjectURL(blob);
			a.href = url;
			a.download = name;
			a.click();
			window.URL.revokeObjectURL(url);
		};
	}());
}
vox_data.export('sample.vox');

`

**Comment by greentec** [comment]
Oh, I remembered. The source code was from quasimondo - one of gurus in AI and computational art field.
https://codepen.io/quasimondo/pen/QjqZvV
