### ISSUE TITLE
.vox files from MagicaVoxel 0.98 do not work

### ISSUE THREAD

**Issue by mgatland** [daishihmr/vox.js#3]
Hi! Thank you for making this useful tool.

vox.js does not work with files from MagicaVoxel 0.98 (Windows version). When I use them in three.js they do not appear in my scene.

This file works great:

https://github.com/ephtracy/voxel-model/blob/master/vox/character/chr_fox.vox

but if I open it using MagicaVoxel 0.98, then save it again, it does not work any more 😞

Should I use an older version of MagicaVoxel instead? Can you tell me what version works?

**Comment by daishihmr** [comment]
Hello. Thank you for using vox.js.
I'm sorry. vox.js does not yet support MagicaVoxel 0.98.
We will correspond within the year, so please use 0.97.x until then.

**Comment by mgatland** [comment]
Thank you!

**Comment by daishihmr** [comment]
Sorry I made you wait! ><
I fixed this bug. Please check newest version.
