### ISSUE TITLE
Face missing after import large file.

### ISSUE THREAD

**Issue by tiaod** [daishihmr/vox.js#4]
![image](https://cloud.githubusercontent.com/assets/7500825/21376038/d50ce0c6-c76c-11e6-8b0f-723eff99e3f2.png)
![image](https://cloud.githubusercontent.com/assets/7500825/21376051/ee88691c-c76c-11e6-93aa-b07fb8e5da59.png)
![image](https://cloud.githubusercontent.com/assets/7500825/21376067/19bafd70-c76d-11e6-854f-942462a958a1.png)
![image](https://cloud.githubusercontent.com/assets/7500825/21376076/206fddde-c76d-11e6-8fe1-00be6decae7d.png)

**Comment by daishihmr** [comment]
Thank you!

I fixed this bug. Please check newest version.

![fix](https://cloud.githubusercontent.com/assets/462290/21379297/44390862-c790-11e6-88b9-3bacceaa8888.png)

**Comment by tiaod** [comment]
![image](https://cloud.githubusercontent.com/assets/7500825/21379462/22df22c0-c789-11e6-8e1b-f7df868f278e.png)
![image](https://cloud.githubusercontent.com/assets/7500825/21379477/3aee4008-c789-11e6-9644-e25ce2b26d73.png)
Awesome! Thank you!
