### ISSUE TITLE
Error: uint8Array index out of bounds: 7888

### ISSUE THREAD

**Issue by edap** [daishihmr/vox.js#7]
I can not load this .vox file
https://github.com/mikelovesrobots/mmmm/blob/master/vox/veh_mini1.vox

the error message is in the title.

it comes from lines 187 `while (chunk(dataHolder));`

**Comment by daishihmr** [comment]
I tried it with the latest version and it was successfully loaded.

Which browser did you test?

**Comment by edap** [comment]
Chrome  58.0.3029.81 on macOS. The last magica voxel version and the last threejs.

**Comment by daishihmr** [comment]
http://private.dev7.jp/vox/voxtest.html

This page shows your data with the latest vox.js and three.js.
Is it displayed correctly?

**Comment by daishihmr** [comment]
![default](https://cloud.githubusercontent.com/assets/462290/25595199/e4425824-2efe-11e7-8fc2-397fcdfe17d5.png)
